services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${WEBHOOK__PORT:-8080}:${WEBHOOK__PORT:-8080}"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    ports:
      - "${DB__PORT:-5434}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
      POSTGRES_DB: ${DB__NAME}
      DB__HOST: ${DB__HOST}
      DB__PORT: ${DB__PORT}

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS__PORT:-6434}:6379"
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: ${REDIS__PASSWORD}
      REDIS__HOST: ${REDIS__HOST}
      REDIS__PORT: ${REDIS__PORT}
      REDIS__DB: ${REDIS__DB}
    command: redis-server --requirepass ${REDIS__PASSWORD}

volumes:
  db_data:
  redis_data: